yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('api/v1/posts/<int:pk>/', views.get_post, name='post_ser'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('auth/', include('users.urls', namespace='auth')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(max_length=50, unique=True, verbose_name='Ссылка')
    description = models.TextField(verbose_name='Описание группы')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текстовое поле текст пост'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Название группы',
        help_text='Это группы'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name = 'Посты'


class Comment(models.Model):
    text = models.TextField(
        max_length=300,
        verbose_name='Комментарий',
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата комментария'
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'

    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        models.UniqueConstraint(
            fields=['user', 'author'], name='already_following'
        )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст вашего поста',
            'group': 'Группа',
            'image': 'Изображение',
        }
        help_texts = {
            'text': 'Начните писать! Вдохновение придёт со временем.',
            'group': 'Пост будет относится к выбранной группе',
            'image': 'Загрузите изображение к посту',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Комментарий'}
        help_texts = {'text': 'Ваш комментарий к посту'}

yatube/posts/views.py
import requests
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post
from .serializers import PostSerializer
from .utils import paginator

User = get_user_model()


@cache_page(1 * 20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.all().select_related('author', 'group')
    page_obj = paginator(post_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all().select_related('author', 'group')
    page_obj = paginator(post_list, request)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all().select_related('group')
    page_obj = paginator(post_list, request)
    failed_message = None
    if request.user.is_authenticated:
        if request.user.id == author.id:
            failed_message = 'Нельзя подписаться на самого себя!'
            follow = None
        else:
            follow = Follow.objects.filter(
                user_id=request.user,
                author_id=author
            ).exists()
    else:
        failed_message = 'Сначала регистрация! :)'
        follow = None
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': follow,
        'failed': failed_message,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment_list = post.comments.all()
    form = CommentForm(
        request.POST or None,
    )
    context = {
        'post': post,
        'comments': comment_list,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            form.save()
            return redirect('posts:profile', post.author)
        return render(request, 'posts/post_create.html', {'form': form})
    return render(request, 'posts/post_create.html',
                  {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    is_edit = True
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'post_id': post_id,
        'is_edit': is_edit,
    }
    return render(request, 'posts/post_create.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator(post_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user.id != author.id:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    unfollowing_author = get_object_or_404(User, username=username)
    get_object_or_404(
        Follow,
        user=request.user,
        author=unfollowing_author
    ).delete()
    return redirect('posts:profile', username=unfollowing_author)


def get_post(request, pk: int):
    if request.method == 'GET':
        post = get_object_or_404(Post, pk=pk)
        serializer = PostSerializer(post)
        return JsonResponse(serializer.data)

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1> Лента подписок {{ text|safe }} </h1>
        {% include 'posts/includes/switcher.html' %}     
        {% for post in page_obj %}  
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>
          {% if post.group %}  
            <a href="{% url 'posts:group' post.group.slug %}"> все записи группы</a>
          {% endif %}
          {% if not forloop.last %} <hr> {% endif %}
        {% endfor %}
        </article>
        {% include 'posts/includes/paginator.html' %}
      </div>  
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} {{ group.title }} {% endblock %}
      {% block content %}    
        <div class="container py-5">
          <h1> Все посты сообщества {{ group.title }} </h1>
            <article>
              <p> {{ group.description }} </p>
            {% for post in page_obj %}
                <ul>
                  <li>
                    Автор: {{ post.author.get_full_name }}
                  </li>
                  <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                  </li>
                </ul>  
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                  <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}    
                <p>
                  {{ post.text }}
                </p>
                {% if post.group %}
                  <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
                {% endif %}
                {% if not forloop.last %} <hr> {% endif %}
            {% endfor %}
            </article>
            {% include 'posts/includes/paginator.html' %} 
        {% endblock %}
      </div>  

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1> Главная страница {{ text|safe }} </h1>
        {% include 'posts/includes/switcher.html' %}
        <article>
        {% for post in page_obj %}  
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>
          {% if post.group %}  
            <a href="{% url 'posts:group' post.group.slug %}"> все записи группы</a>
          {% endif %}
          {% if not forloop.last %} <hr> {% endif %}
        {% endfor %}
        </article>
        {% include 'posts/includes/paginator.html' %}
      </div>  
{% endblock content %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}

<main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if is_edit %}
                Редактируем пост
              {%else %}
                Добавить новый пост
              {% endif %}           
            </div>
            <div class="card-body">  
              {% if is_edit %}      
                <form method="post" action="{% url 'posts:post_edit' post_id %}" enctype="multipart/form-data">
              {% else %}
                <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">    
              {% endif %}
              {% csrf_token %}
                <input type="hidden" name="" value="">            
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    {{ form.text.label|safe }} 
                    <span class="required text-danger" >*</span>                  
                  </label>
                    {{ form.text }}  
                  <small id="id_text-help" class="form-text text-muted">
                    {{ form.text.help_text|safe }}
                  </small>                  
                </div>            
                <div class="form-group row my-3 p-3">
                  <label for="id_group">
                    {{ form.group.label|safe }}                  
                  </label>
                  <select name="group" class="form-control" id="id_group">
                    <option value="" selected>  </option>
                    <option value=""> {% for group in form.group %} {{ group }} {% endfor %} </option>                    
                  </select>
                  <small id="id_group-help" class="form-text text-muted">
                    {{ form.group.help_text|safe }}
                  </small>
                </div>
                  <p> {{ form.image }}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}   
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} {{ post.text|slice:":30" }} {% endblock %}
{% block content %}
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            <li class="list-group-item">
              {% if post.group %}
                Группа: {{ post.group }}
              <p>  
              <a href="{% url 'posts:group' post.group.slug %}"> все записи группы </a
              {% endif %}
              </a>
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span style="color: green"> {{ post.author.posts.count }} </span>
            </li>
            <li class="list-group-item">

              <a href="{% url 'posts:profile' post.author.username %}"> 
                все посты пользователя 
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p> {{ post.text }} </p>
          <h4> Комментарии </h4>
          {% for comment in comments %} 
            <p> {{ comment.author }}: {{ comment.text }} </p>
            <p> Дата: {{ comment.created }}
          {% endfor %}
          <form method="post" action="{% url 'posts:add_comment' post.pk %}">
          {% csrf_token %}
          <input type="hidden" name="" value="">            
          <div class="form-group row my-3 p-3">
            <label for="id_text"> 
              <span class="required text-danger" >*</span>                  
            </label>
              {{ form.text }}  
            <small id="id_text-help" class="form-text text-muted">
            </small>     
            <button type="submit" class="btn btn-primary">
              Отправить
            </button>             
          </div>            
          <div class="form-group row my-3 p-3">
        </article>
      </div> 
    </main>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Профайл пользователя {{ author.get_full_name }} {% endblock %}
{% block content %}
    <main>
      <div class="container py-5">        
        <h1>Все посты пользователя {{ post.author.get_full_name }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
        {{ failed|default_if_none:'' }}
        {% for post in page_obj %}   
        <article>  
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <p>
                <a href="{% url 'posts:profile' post.author.username %}"> все посты пользователя </a>
              </p>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
          </ul>
          <p>
            {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
          <p>
            {% if post.group %}  
              <a href="{% url 'posts:group' post.group.slug %}"> все записи группы</a>
            {% endif %}
          </p>
          {% if not forloop.last %}      
          <hr> {% endif %}
        {% endfor %}
        </article>  
        {% include 'posts/includes/paginator.html' %}
      </div>
    </main>

{% endblock content %}